#!/bin/sh

diffJSFiles=$(git diff --stage --diff-filter=AM --name-only | grep ".js$" | xargs)
if [[ $diffJSFiles == "" ]]
then
	exit 0
fi

for f in $diffJSFiles
do
	git show :$f | eslint --stdin --stdin-filename=$f
	if [[ $? -ne 0 ]]
	then
		exit 1
	fi
done

