#!/bin/sh

diffJSFiles=$(git diff --staged --diff-filter=AM --name-only | grep ".js$" | xargs)
if [[ $diffJSFiles == "" ]]
then
	exit 0
fi

for f in $diffJSFiles
do
	echo $f
	git show :$f | unix2dos | eslint --stdin --stdin-filename=$f
	if [[ $? -ne 0 ]]
	then
		exit 1
	fi
done

